name: Update Quote SVG

on:
  schedule:
    - cron: '0 0 * * *'  # 每天执行
  workflow_dispatch:

jobs:
  update-quote-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch quote and generate SVG
        run: |
          # 获取诗句
          QUOTE_DATA=$(curl -s 'https://v1.hitokoto.cn/?c=i')
          QUOTE=$(echo "$QUOTE_DATA" | jq -r '.hitokoto')
          SOURCE=$(echo "$QUOTE_DATA" | jq -r '.from')
          AUTHOR=$(echo "$QUOTE_DATA" | jq -r '.from_who')
          
          # 如果作者为空，使用"佚名"
          if [ "$AUTHOR" = "null" ]; then
            AUTHOR="佚名"
          fi
          
          # 生成SVG
          cat > .github/quote.svg << EOF
          <svg width="800" height="200" xmlns="http://www.w3.org/2000/svg">
            <style>
              @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+SC:wght@300;400&amp;display=swap');
              
              .background {
                fill: #f8f8f8;
                rx: 10;
                ry: 10;
              }
              .quote {
                font-family: 'Noto Serif SC', 'FangSong', serif;
                font-size: 24px;
                font-weight: 300;
                fill: #333333;
                text-anchor: middle;
                letter-spacing: 2px;
              }
              .author {
                font-family: 'Noto Serif SC', 'KaiTi', serif;
                font-size: 16px;
                font-weight: 300;
                fill: #666666;
                text-anchor: end;
              }
              .dot {
                fill: #999999;
              }
              .decoration {
                stroke: #e0e0e0;
                stroke-width: 1;
              }
            </style>
            
            <!-- 极简背景 -->
            <rect width="100%" height="100%" fill="white"/>
            <rect x="10" y="10" width="780" height="180" class="background"/>
            
            <!-- 中心线条装饰 -->
            <line x1="150" y1="100" x2="650" y2="100" class="decoration" stroke-dasharray="1,3" opacity="0.5"/>
            
            <!-- 简约圆点装饰 -->
            <circle cx="150" cy="100" r="3" class="dot" opacity="0.7"/>
            <circle cx="650" cy="100" r="3" class="dot" opacity="0.7"/>
            
            <!-- 诗句 -->
            <text x="400" y="95" class="quote">${QUOTE}</text>
            
            <!-- 作者和出处 -->
            <text x="650" y="150" class="author">— ${AUTHOR}《${SOURCE}》</text>
          </svg>
          EOF
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .github/quote.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update daily quote SVG"
          git push
